// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Win21Pages.Models
{
    public partial class Post
    {
        public int Id { get; set; }
        public string PostName { get; set; }
        public DateTime UploadDate { get; set; }
        public string PostUrl { get; set; }
        public string PostSize { get; set; }
        public string UserId { get; set; }
    }
}